### ISSUE TITLE
Do you really require @dev constraints?

### ISSUE THREAD

**Issue by chillu** [dynamic/silverstripe-elemental-blocks#110]
Looking at the `composer.json`, there's a lot of `@dev`. Which breaks anyone trying to use those stable module tags (e.g. `3.0.0`) with stable core dependencies (like `cms:4.3.2@stable`). If you're actually relying on unreleased versions of those dependencies, it might be a good idea to hold off tagging your own stable releases? In the more likely case that you're not relying on it, could you please remove the `@dev` and tag that as `3.0.1`?

**Comment by muskie9** [comment]
Thanks for the suggestion @chillu, I don't know that there's a good reason outside of the upgrade transition period while we were getting everything working with SilverStripe 4. I'll confirm with the team and we'll get updated releases where needed.

**Comment by chillu** [comment]
Awesome, thanks Nic! I realised that's the case for a lot of the other (super awesome) blocks modules in `dynamic` as well. By the way, I've used some of your modules in a sales pitch yesterday, great to be able to wow people with community-built features!

**Comment by mak001** [comment]
We should also check for `PHPUnit` in composer instead of `phpunit` as the former throws warnings.

**Comment by muskie9** [comment]
@chillu we've gone through our elemental modules and have resolved the dev constraint. Let us know if you come across any issues with the latest tags.

**Comment by chillu** [comment]
Wow, so many PRs! Thanks heaps :)
