### ISSUE TITLE
Submit module to Packagist

### ISSUE THREAD

**Issue by hdpero** [dynamic/silverstripe-elemental-blocks#32]
Hi,
when running `composer require dynamic/dynamic-elements` **(on clean SilverStripe 4 installation)** I'm getting an error:
```Problem 1:  the requested package dynamic/dynamic-elements could not be found in any version, there may be a typo on package name.```

I have tried to search module on Packagist, and didn't find any results.
What did work for me is adding a `repositories` line to my project composer.json file like so:
```json
"repositories": [{
    "type": "git",
    "url": "https://github.com/dynamic/dynamic-elements/"
}],
"require": {
    "php": ">=5.6.0",
    "silverstripe/recipe-cms": "1.0.0@stable",
    "dynamic/dynamic-elements": "2.0.x-dev"
}
```

**Comment by hdpero** [comment]
Hi @jsirish @muskie9 do you guys have any comments or thoughts on my issue?

**Comment by jsirish** [comment]
Hi @hdpero

Thanks for submitting an issue. We’re actively working towards an alpha release, at which point we’ll add the module to packagist. In the meantime, the method you’re using is the same way we’re pulling it in. 

We’ll close this issue once it’s in packagist. 

Thanks!

**Comment by jsirish** [comment]
this has been added to packagist as dynamic/silverstripe-elemental-blocks
