### ISSUE TITLE
New Accordion Panel - Save and Publish browser error

### ISSUE THREAD

**Issue by hdpero** [dynamic/silverstripe-elemental-blocks#33]
When I'm trying to Save and Publish newly created Accordion Panel, I'm getting a browser error:
![accordion-browser-warning-save-and-publish](https://user-images.githubusercontent.com/13778690/33799895-ed8ac850-dd34-11e7-9c33-cfb3bd835a48.png)

I'm running:
- SilverStripe 4.0.1
- Windows 10
- WAMP 3.1.0 (PHP 5.6.31 , MySQL 5.7.19)
- Chrome 62.0.3202.94

But when I click **"Ok"**  everything seems to Save and Publish without a hitch.  

My guess is Session or Cookie problem.

**Comment by hdpero** [comment]
As a reference I'm adding a ["solved" issue here](https://github.com/symbiote/silverstripe-gridfieldextensions/issues/226)

**Comment by jsirish** [comment]
hi @hdpero 

This seems to be resolved. Let us know if you still run into this in the latest version. Thanks!
