### ISSUE TITLE
REFACTOR break out elements into separate modules

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-elemental-blocks#86]
**To Split Out**

- [x] ElementAccordion
- [x] ElementCountDown
- [x] ElementCustomerService
- [x] ElementEmbeddedCode
- [x] ElementOembed
- [x] ElementPhotoGallery

**Up for full removal**

- [x] ElementCallToAction

**Needs for migration**

Task to handle updating FQN's in the database.

# Update

We will essentially break out each elemental block and this will become a recipe requiring all of our elemental blocks. This will provide both independent flexibility as well as a holistic solution for those that want it.

**Comment by jsirish** [comment]
complete
